### ISSUE TITLE
Automatic duplication of timetables or referencing existing timetables

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#390] opened 2017-05-24 12:55 UTC
When making a new line, you might want the same frequencies and inter-stop times at e.g. 5-6 AM and 11pm. Currently you need to re-type everything repeatedly.

**Comment by mattwigway** [comment] 2017-05-24 14:16
Duplicate of #264.

**Closed by mattwigway** 2017-05-24 14:16 UTC

**Comment by abyrd** [comment] 2017-05-24 14:30
Sorry about any duplicates, I was just firing these off during a conversion to make sure they got recorded.
