### ISSUE TITLE
Issue with screen layout

### ISSUE THREAD

**Issue by landonreed** [conveyal/analysis-ui#265] opened 2017-01-30 17:43 UTC
See screenshot for issue viewing UI on my laptop screen.  The header/navbar appears to get cut off.  It didn't appear this way at first.  It first occurred, I think, when I switched to analysis mode for the first time.  Reloading does not help.

![image](https://cloud.githubusercontent.com/assets/2370911/22434278/6302712a-e6e9-11e6-9b43-0e20f5f61346.png)

**Comment by mattwigway** [comment] 2017-01-30 17:44
Duplicate of #250.

**Closed by mattwigway** 2017-01-30 17:44 UTC
