### ISSUE TITLE
Cannot load modification

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#454] opened 2017-07-19 21:47 UTC
Somehow this adjust-dwell-time modification is no good and won't load in the front end (demo account): https://analysis.conveyal.com/scenarios/05549740-341d-45af-8e59-8555c7e35801/modifications/60213445-13d4-4251-928c-b0a06c8fa0c0

**Comment by mattwigway** [comment] 2017-07-21 11:34
I can't delete it either, because the delete button doesn't show up (hidden by the perpetual loading message). It's preventing analysis on this scenario.

**Comment by mattwigway** [comment] 2017-07-21 14:39
Here's the modification JSON as returned by the server:

```{
  "id": "60213445-13d4-4251-928c-b0a06c8fa0c0",
  "showOnMap": false,
  "expanded": false,
  "variants": [
    true,
    true,
    true
  ],
  "scenario": "05549740-341d-45af-8e59-8555c7e35801",
  "description": null,
  "name": "Adjust Dwell Time",
  "feed": "6724975c-b181-4507-acc4-271d74588c7f",
  "routes": null,
  "trips": null,
  "stops": null,
  "scale": false,
  "value": 30,
  "type": "adjust-dwell-time"
}
```

**Comment by trevorgerhardt** [comment] 2017-08-21 12:03
Unable to reproduce this locally in the latest code with an identical response object. It's unusual in that there is no error occurring. I am going to close this for now as it may be an artifact of the previously deployed UI code.

**Closed by trevorgerhardt** 2017-08-21 12:03 UTC
