### ISSUE TITLE
Auto-created stops not distinguished from manually placed stops in add trip pattern mods

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1076] opened 2020-04-18 16:25 UTC
Auto-created stops are using the same symbol as manually placed stops. This is only the case for Add Trip Pattern modifications:
![Screenshot_2020-04-18_12-19-19](https://user-images.githubusercontent.com/7830465/79643033-faa93400-816e-11ea-8114-eded108378c1.png)

Reroute modifications use a different symbol, as the legend indicates:
![Screenshot_2020-04-18_12-23-02](https://user-images.githubusercontent.com/7830465/79643140-815e1100-816f-11ea-8b03-4b41a1e70759.png)

**Comment by trevorgerhardt** [comment] 2020-06-16 04:02
I originally couldn't reproduce. And now it appears you cannot either. Closing

**Closed by trevorgerhardt** 2020-06-16 04:02 UTC
Labels: bug
