### ISSUE TITLE
Regional analysis comparison map legend should show analysis names

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1182] opened 2020-08-11 18:51 UTC
The common use case is comparing different analyses. The legend isn't informative if it only shows "Jobs within 45 minutes, 50th percentile minus Jobs within 45 minutes, 50th percentile" without the analysis names.

**Comment by trevorgerhardt** [comment] 2020-08-13 04:16
I agree, it looks better with the names. I wonder if there's a more compact way to represent all of this, especially because it is technically a duplicate of information that exists in the sidebar:

<img width="335" alt="Screen Shot 2020-08-13 at 12 13 41" src="https://user-images.githubusercontent.com/776780/90093544-718dbc80-dd5e-11ea-9584-a985fe6d3685.png">

Thoughts on this @ansoncfit ?

**Comment by ansoncfit** [comment] 2020-08-13 04:17
I think some duplication is permissible, given our expectations that users may want to take a screenshot of just the map + legend.

**Closed** 2020-08-13 05:21 UTC
Labels: UX, cleanup
