### ISSUE TITLE
show result values on mouseover

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#689] opened 2018-05-13 23:59 UTC
When browsing regional analysis results we see only the choropleths on the map, but no specific values. It would be nice to continuously show the value under the cursor (maybe somewhere off to the side or bottom) and pop up persistent values in markers where you click.

**Comment by ansoncfit** [comment] 2018-09-26 17:27
Similarly, when viewing an isochrone, we should show travel time value(s).  The box plot component we used to use seems to have disappeared.  I found that helpful in explaining the distribution of travel times to people, and we should bring back this functionality in some form.

**Comment by abyrd** [comment] 2018-10-03 06:21
This box plot that would show over the single point isochrones would be very helpful for debugging as well. @trevorgerhardt was there an intentional decision to remove it or did it just stop working?

**Comment by ansoncfit** [comment] 2020-10-08 01:23
Single-point version resolved in https://github.com/conveyal/analysis-ui/pull/1224

Regional version duplicate of #436

**Closed by ansoncfit** 2020-10-08 01:23 UTC
Labels: feature, wontfix
