### ISSUE TITLE
Isochrone display problem at high travel times with transit disabled

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#665] opened 2018-03-28 08:54 UTC

**Comment by ansoncfit** [comment] 2018-04-18 13:07
See discussion at https://github.com/conveyal/r5/issues/360

> Since in the UI we use single bytes for travel times in minutes, anything over about 2 hours is subject to overflow so maybe we should add some additional checks.

**Comment by trevorgerhardt** [comment] 2018-11-12 09:20
This issue needs more information and specifics before it can be worked on. Is there a concrete example where we are sure that is the UIs problem?

**Comment by ansoncfit** [comment] 2018-11-12 16:33
Reproducible on staging (Test Region - Boston, Project 1, with all transit modes disabled).  Note the "reachable" area in the northeast corner.  


![image](https://user-images.githubusercontent.com/2173529/48360910-3da7d380-e66e-11e8-8268-577cf55c0f36.png)

**Comment by abyrd** [comment] 2019-05-07 14:44
The above commit implies this might be due to overflowing a signed byte. We should add some sanity checks to ensure negative travel times are never encoded.

**Comment by ansoncfit** [comment] 2019-06-03 12:46
Recent testing in Sydney with R5 version `v4.5.3-73-g70490cc` suggests the issue is still present, so the commit above in which I referenced a possible fix did not actually resolve the issue.

**Comment by ansoncfit** [comment] 2019-06-05 02:35
Note that the stray areas of reachability generally appear in areas with sparse road networks or long edges, when transit is disabled.

An example of a 120 minute walk-only isochrone from a point in New South Wales:
![image](https://user-images.githubusercontent.com/2173529/58924127-92955f00-8710-11e9-9ae4-722598d43e30.png)

![image](https://user-images.githubusercontent.com/2173529/58924298-557d9c80-8711-11e9-985a-4c253d44c43d.png)

Comparing downloaded geotiff travel time surface and reveals a couple issues:
- The stray areas of reachability correspond to areas reachable in ~255 minutes, suggesting an overflow issue is at play.
- It appears R5 uses `maxTripDurationMinutes` as a limit on the street router, but it the does not check whether `maxTripDurationMinutes` is exceeded after adding in distances between vertices and linked points.

**Comment by abyrd** [comment] 2019-06-05 09:09
Nice visualization. The idea that a travel time check is performed on the transit results, but not on the transit+egress results explains why we'd see isolated small islands instead of a continuous ring of overflow accessibility. 

Some observations: we generally don't allow selecting travel times over 2 hours so all values over 120 can't even be displayed in the UI. Cutting off the search at 120 minutes would probably make it significantly faster. Related: Java has only signed bytes, so the values 127 < n < 255 are actually negative numbers -255 through -1 from Java's point of view, but I believe careful handling ensures these make it out to the Javascript UI intact where they are interpreted as unsigned (positive) bytes. We could avoid some sources of confusion if we restricted everything to just the lower 7 bits by applying a hard cutoff to searches at 120 minutes.

However, if I remember right we may have only recently lifted this limit on request to deal with long travel times in Australia.

**Comment by ansoncfit** [comment] 2019-07-19 03:49
Closed in R5 v4.6.0

**Closed by ansoncfit** 2019-07-19 03:49 UTC
Labels: bug, need info
