### ISSUE TITLE
Create stops automatically does not avoid automatically created stops

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#414] opened 2017-06-02 13:29 UTC
It used to be that automatically created stops would be skipped if they fell with 1/4 of the stop spacing distance of a bona fide stop, this appears to no longer be working.

![image](https://cloud.githubusercontent.com/assets/566958/26727778/fe13a1ce-4775-11e7-85d8-b0658ba9f0cb.png)

**Comment by trevorgerhardt** [comment] 2017-06-02 14:54
Is it possible to create a test for this @mattwigway? Assuming that we don't currently have one and that it should be broken if the logic has changed.

**Comment by trevorgerhardt** [comment] 2017-06-30 22:07
Also, I cannot reproduce this at the moment, so I'll close it for now.

**Closed by trevorgerhardt** 2017-06-30 22:07 UTC
